vich_uploader:
    db_driver: orm

    mappings:
       media_object:
           uri_prefix: /api/public/media/posters
           upload_destination: '%kernel.project_dir%/public/media/posters'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       report_object:
           uri_prefix: /api/public/media/reports
           upload_destination: '%kernel.project_dir%/public/media/reports'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       resolution_object:
           uri_prefix: /api/public/media/resolutions
           upload_destination: '%kernel.project_dir%/public/media/resolutions'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
