<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250930101607 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ballot_result ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE board_member ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN candidate.withdrew_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN candidate.winner_marked_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN candidate.rejected_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN election.evaluated_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN election.completed_at IS \'\'');
        $this->addSql('ALTER TABLE media_poster ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE media_report ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN media_report.published_at IS \'\'');
        $this->addSql('ALTER TABLE media_resolution ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN media_resolution.published_at IS \'\'');
        $this->addSql('ALTER TABLE "position" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN vote.invalidated_at IS \'\'');
        $this->addSql('ALTER TABLE async_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE async_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN async_messages.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN async_messages.available_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN async_messages.delivered_at IS \'\'');
        $this->addSql('ALTER TABLE async_messages_failed ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE async_messages_failed ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN async_messages_failed.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN async_messages_failed.available_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN async_messages_failed.delivered_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE async_messages ALTER id SET DEFAULT nextval(\'async_messages_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE async_messages ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN async_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN async_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN async_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE async_messages_failed ALTER id SET DEFAULT nextval(\'async_messages_failed_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE async_messages_failed ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN async_messages_failed.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN async_messages_failed.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN async_messages_failed.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE ballot_result ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE board_member ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN candidate.withdrew_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN candidate.rejected_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN candidate.winner_marked_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN election.evaluated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN election.completed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE media_poster ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE media_report ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN media_report.published_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE media_resolution ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN media_resolution.published_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE position ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN vote.invalidated_at IS \'(DC2Type:datetime_immutable)\'');
    }
}
